/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxComponent: typeof import('./src/components/CheckboxComponent.vue')['default']
    CreateOptionsAndVariantsPanel: typeof import('./src/components/CreateOptionsAndVariantsPanel.vue')['default']
    CreateOptionsPanel: typeof import('./src/components/CreateOptionsPanel.vue')['default']
    CreateProductOptionPanel: typeof import('./src/components/CreateProductOptionPanel.vue')['default']
    CreateProductOptionsPanel: typeof import('./src/components/CreateProductOptionsPanel.vue')['default']
    EditVariantDialog: typeof import('./src/components/EditVariantDialog.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    InventoryPanel: typeof import('./src/components/InventoryPanel.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PriceCell: typeof import('./src/components/cells/PriceCell.vue')['default']
    PriceInput: typeof import('./src/components/PriceInput.vue')['default']
    PricingInput: typeof import('./src/components/PricingInput.vue')['default']
    PricingPanel: typeof import('./src/components/PricingPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLabel: typeof import('./src/components/StatusLabel.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TagCell: typeof import('./src/components/cells/TagCell.vue')['default']
    TitleAndDescription: typeof import('./src/components/TitleAndDescription.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const CheckboxComponent: typeof import('./src/components/CheckboxComponent.vue')['default']
  const CreateOptionsAndVariantsPanel: typeof import('./src/components/CreateOptionsAndVariantsPanel.vue')['default']
  const CreateOptionsPanel: typeof import('./src/components/CreateOptionsPanel.vue')['default']
  const CreateProductOptionPanel: typeof import('./src/components/CreateProductOptionPanel.vue')['default']
  const CreateProductOptionsPanel: typeof import('./src/components/CreateProductOptionsPanel.vue')['default']
  const EditVariantDialog: typeof import('./src/components/EditVariantDialog.vue')['default']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
  const InventoryPanel: typeof import('./src/components/InventoryPanel.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const PriceCell: typeof import('./src/components/cells/PriceCell.vue')['default']
  const PriceInput: typeof import('./src/components/PriceInput.vue')['default']
  const PricingInput: typeof import('./src/components/PricingInput.vue')['default']
  const PricingPanel: typeof import('./src/components/PricingPanel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const StatusLabel: typeof import('./src/components/StatusLabel.vue')['default']
  const TableComponent: typeof import('./src/components/TableComponent.vue')['default']
  const TagCell: typeof import('./src/components/cells/TagCell.vue')['default']
  const TitleAndDescription: typeof import('./src/components/TitleAndDescription.vue')['default']
}