/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxComponent: typeof import('./src/components/CheckboxComponent.vue')['default']
    CheckboxInput: typeof import('./src/components/CheckboxInput.vue')['default']
    CreateOptionDialog: typeof import('./src/components/dialogs/CreateOptionDialog.vue')['default']
    CreateOptionsAndVariantsPanel: typeof import('./src/components/CreateOptionsAndVariantsPanel.vue')['default']
    CreateOptionsPanel: typeof import('./src/components/CreateOptionsPanel.vue')['default']
    CreateProductOptionPanel: typeof import('./src/components/CreateProductOptionPanel.vue')['default']
    CreateProductOptionsPanel: typeof import('./src/components/CreateProductOptionsPanel.vue')['default']
    CreateVariantDialog: typeof import('./src/components/dialogs/CreateVariantDialog.vue')['default']
    EditNewProductVariant: typeof import('./src/components/dialogs/EditNewProductVariant.vue')['default']
    EditOptionDialog: typeof import('./src/components/dialogs/EditOptionDialog.vue')['default']
    EditProductCollectionsDialog: typeof import('./src/components/dialogs/EditProductCollectionsDialog.vue')['default']
    EditProductDialog: typeof import('./src/components/dialogs/EditProductDialog.vue')['default']
    EditStatusDialog: typeof import('./src/components/dialogs/EditStatusDialog.vue')['default']
    EditVariantDialog: typeof import('./src/components/dialogs/EditVariantDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    InventoryPanel: typeof import('./src/components/InventoryPanel.vue')['default']
    ItemActions: typeof import('./src/components/ItemActions.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PriceCell: typeof import('./src/components/cells/PriceCell.vue')['default']
    PriceInput: typeof import('./src/components/PriceInput.vue')['default']
    PricingInput: typeof import('./src/components/PricingInput.vue')['default']
    PricingPanel: typeof import('./src/components/PricingPanel.vue')['default']
    ProfileMenu: typeof import('./src/components/ProfileMenu.vue')['default']
    PromptLoginDialog: typeof import('./src/components/dialogs/PromptLoginDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowActions: typeof import('./src/components/RowActions.vue')['default']
    StatusLabel: typeof import('./src/components/StatusLabel.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TagCell: typeof import('./src/components/cells/TagCell.vue')['default']
    TanstackTable: typeof import('./src/components/TanstackTable.vue')['default']
    TitleAndDescription: typeof import('./src/components/TitleAndDescription.vue')['default']
    VariantOptionSelect: typeof import('./src/components/VariantOptionSelect.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const CheckboxComponent: typeof import('./src/components/CheckboxComponent.vue')['default']
  const CheckboxInput: typeof import('./src/components/CheckboxInput.vue')['default']
  const CreateOptionDialog: typeof import('./src/components/dialogs/CreateOptionDialog.vue')['default']
  const CreateOptionsAndVariantsPanel: typeof import('./src/components/CreateOptionsAndVariantsPanel.vue')['default']
  const CreateOptionsPanel: typeof import('./src/components/CreateOptionsPanel.vue')['default']
  const CreateProductOptionPanel: typeof import('./src/components/CreateProductOptionPanel.vue')['default']
  const CreateProductOptionsPanel: typeof import('./src/components/CreateProductOptionsPanel.vue')['default']
  const CreateVariantDialog: typeof import('./src/components/dialogs/CreateVariantDialog.vue')['default']
  const EditNewProductVariant: typeof import('./src/components/dialogs/EditNewProductVariant.vue')['default']
  const EditOptionDialog: typeof import('./src/components/dialogs/EditOptionDialog.vue')['default']
  const EditProductCollectionsDialog: typeof import('./src/components/dialogs/EditProductCollectionsDialog.vue')['default']
  const EditProductDialog: typeof import('./src/components/dialogs/EditProductDialog.vue')['default']
  const EditStatusDialog: typeof import('./src/components/dialogs/EditStatusDialog.vue')['default']
  const EditVariantDialog: typeof import('./src/components/dialogs/EditVariantDialog.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
  const InventoryPanel: typeof import('./src/components/InventoryPanel.vue')['default']
  const ItemActions: typeof import('./src/components/ItemActions.vue')['default']
  const LoginButton: typeof import('./src/components/LoginButton.vue')['default']
  const LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const PriceCell: typeof import('./src/components/cells/PriceCell.vue')['default']
  const PriceInput: typeof import('./src/components/PriceInput.vue')['default']
  const PricingInput: typeof import('./src/components/PricingInput.vue')['default']
  const PricingPanel: typeof import('./src/components/PricingPanel.vue')['default']
  const ProfileMenu: typeof import('./src/components/ProfileMenu.vue')['default']
  const PromptLoginDialog: typeof import('./src/components/dialogs/PromptLoginDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RowActions: typeof import('./src/components/RowActions.vue')['default']
  const StatusLabel: typeof import('./src/components/StatusLabel.vue')['default']
  const TableComponent: typeof import('./src/components/TableComponent.vue')['default']
  const TagCell: typeof import('./src/components/cells/TagCell.vue')['default']
  const TanstackTable: typeof import('./src/components/TanstackTable.vue')['default']
  const TitleAndDescription: typeof import('./src/components/TitleAndDescription.vue')['default']
  const VariantOptionSelect: typeof import('./src/components/VariantOptionSelect.vue')['default']
}